site_name: 沈檀的妙妙屋
site_url: https://santal0.github.io/
markdown_extensions:
  - neoteroi.cards
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - css/cards.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
theme:
  logo: assets/pictures/logo.jpg
  name: material
  language: zh
  features:
    - navigation.sections
    - toc.integrate
  custom_dir: docs/overrides # 评论系统
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: cyan
      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      accent: orange
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: cyan
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
nav:
  - 首页: index.md
  - 课程: 
    - 编译原理:
      - chapter2 词法分析: ./courses/CompilerPrinciple/chapter2.md
      - chapter3 语法分析: ./courses/CompilerPrinciple/Chapter3.md
      - chapter4 抽象语法: ./courses/CompilerPrinciple/Chapter4.md
      - chapter5 语义分析: ./courses/CompilerPrinciple/Chapter5.md
      - chapter6 : ./courses/CompilerPrinciple/Chapter6.md
      - chapter7 中间代码生成: ./courses/CompilerPrinciple/Chapter7.md
      - chapter8 基本块: ./courses/CompilerPrinciple/Chapter8.md
      - chapter9 指令选择: ./courses/CompilerPrinciple/Chapter9.md
      - chapter10 Liveness Analysis（活跃分析）: ./courses/CompilerPrinciple/Chapter10.md
      - chapter11 寄存器分配: ./courses/CompilerPrinciple/Chapter11.md
      - Tiger 语言: ./courses/CompilerPrinciple/Tiger.md
  - cs 相关: 
    - Git 速查: ./cs/Git.md
    - Linux 速查: ./cs/Linux.md
    - Vim 速查: ./cs/Vim.md
    - CMake 速查: ./cs/CMake.md
  - 奇妙技能: 
    - 如何制作网站: ./skills/MakeSite.md
  - 友站: ./friends.md
  - 杂书:
    - 社会科学:
      - 《韧性：县乡政府如何运行》: ./books/political/韧性：县乡政府如何运行.md
